using Business.Interfaces;
using Business.Services;
using Data.Contexts;
using Data.Entities;
using Data.Repositories;
using Domain.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Rewrite;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddControllersWithViews();

builder.Services.AddDbContext<AppDbContext>(x =>
    x.UseSqlServer(builder.Configuration.GetConnectionString("SqlConnection"))
        .EnableSensitiveDataLogging()
        .LogTo(Console.WriteLine, LogLevel.Information)
        .EnableDetailedErrors()
);
builder
    .Services.AddIdentity<UserEntity, IdentityRole>(x =>
    {
        x.User.RequireUniqueEmail = true;
        x.Password.RequiredLength = 8;
    })
    .AddEntityFrameworkStores<AppDbContext>()
    .AddDefaultTokenProviders();
builder.Services.ConfigureApplicationCookie(x =>
{
    x.LoginPath = "/Auth/SignIn";
    x.AccessDeniedPath = "/Auth/SignIn";
    x.Cookie.HttpOnly = true;
    x.Cookie.IsEssential = true;
    x.ExpireTimeSpan = TimeSpan.FromHours(1);
    x.SlidingExpiration = true;
});

builder.Services.AddScoped<IClientRepository, ClientRepository>();
builder.Services.AddScoped<IProjectRepository, ProjectRepository>();
builder.Services.AddScoped<IStatusRepository, StatusRepository>();
builder.Services.AddScoped<IUserRepository, UserRepository>();
builder.Services.AddScoped<IClientService, ClientService>();
builder.Services.AddScoped<IProjectService, ProjectService>();
builder.Services.AddScoped<IStatusService, StatusService>();
builder.Services.AddScoped<IUserService, UserService>();
builder.Services.AddScoped<IAuthService, AuthService>();

var app = builder.Build();

app.UseHsts();
app.UseHttpsRedirection();
app.UseRouting();

app.UseAuthentication();
app.UseAuthorization();

app.MapStaticAssets();

app.UseRewriter(new RewriteOptions().AddRedirect("^$", "/Projects/Index"));

app.MapControllerRoute(name: "default", pattern: "{controller=Home}/{action=Index}/{id?}")
    .WithStaticAssets();

// Clients generated by ChatGPT with seed data
using (var scope = app.Services.CreateScope())
{
    var dbCtx = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    var clientService = scope.ServiceProvider.GetRequiredService<IClientService>();
    var userManager = scope.ServiceProvider.GetRequiredService<UserManager<UserEntity>>();

    // Create two example clients if they don't already exist
    if (!(await dbCtx.Clients.AnyAsync(c => c.ClientName == "Acme Corp")))
        await clientService.CreateClientAsync(new ClientFormData { ClientName = "Acme Corp" });

    if (!(await dbCtx.Clients.AnyAsync(c => c.ClientName == "Contoso Ltd")))
        await clientService.CreateClientAsync(new ClientFormData { ClientName = "Contoso Ltd" });
}

app.Run();
